# Generated by Django 4.2.16 on 2024-12-01 17:21

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_path', models.FileField(upload_to='document_storage/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
