# Generated by Django 5.1.3 on 2024-11-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
